repos:
- repo: https://github.com/rubocop/rubocop
  rev: v1.66.1
  hooks:
    - id: rubocop
      # Error, Fatal, Warn, etc.
      args: [--fail-level, E]
      additional_dependencies:
        - rubocop-rails
        - rubocop-rspec
