name: pre-commit-v3

on:
  push:

jobs:
  pre-commit-v3:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      pull-requests: read
      statuses: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install python for pre-commit install
      uses: actions/setup-python@v3

    - name: Install pre-commit
      run: python -m pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always

    - name: Get pre-commit version
      run: pre-commit --version
    - name: Get ruby version
      run: which -a ruby && ruby --version
